version: '3'

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444

  ##########################################
  # Kong: The missing UI for the API Gateway
  ##########################################
  kong-ui:
    image: pantsel/konga
    container_name: kong-ui
    volumes:
      - ./resources/kong-ui/default-node.data:/apps/konga/default-node.data
      - ./resources/kong-ui/default-user.data:/apps/konga/default-user.data
    environment:
      KONGA_SEED_USER_DATA_SOURCE_FILE: /apps/konga/default-user.data
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /apps/konga/default-node.data
    ports:
      - 8002:1337
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  #######################################
  # Keycloak: The SSO Server for auth
  #######################################
  keycloak:
    container_name: keycloak
    restart: on-failure
    image: jboss/keycloak:7.0.1
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - kong

  #######################################
  # Setup routeing for application
  #######################################
  setup-routes:
    container_name: setup-routes
    restart: on-failure
    command: sh /etc/routes.sh
    volumes:
      - ./resources/kong/routes.sh:/etc/routes.sh
    image: curlimages/curl
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - kong