version: '3.4'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: 'kong'
      POSTGRES_PASSWORD: 'kong'
      POSTGRES_USER: 'kong'
    ports:
      - 5432:5432
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  kong-keycloak:
    image: kong-keycloak:1.0
    container_name: kong-keycloak
    volumes:
      - ./resources/kong-keycloak/custom-entrypoint.sh:/root/apps/custom-entrypoint.sh
    environment:
      PG_SERVER_HOST: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: kong
      DB_USER: kong
      DB_PASSWORD: kong
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - 443:443
      - 8000:8000
      - 8001:8001
      - 8080:8080
      - 8443:8443
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
      - postgres

  kong-ui:
    image: pantsel/konga
    container_name: kong-ui
    volumes:
      - ./resources/kong-ui/default-node.data:/apps/konga/default-node.data
      - ./resources/kong-ui/default-user.data:/apps/konga/default-user.data
    environment:
      KONGA_SEED_USER_DATA_SOURCE_FILE: /apps/konga/default-user.data
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /apps/konga/default-node.data
    ports:
      - 8002:1337
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  auth-server:
    image: multi-tenant-auth-server:1.0
    container_name: auth-server
    volumes:
      - ~/keycloak/realms:/root/keycloak/realms
    ports:
      - 9090:9090
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1